name: qp_finance
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  gap: ^3.0.1
  scroll_wheel_date_picker: ^0.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SfProDisplay
      fonts:
        - asset: assets/fonts/SfProDisplay-Regular.otf
          weight: 500
        - asset: assets/fonts/SfProDisplay-Medium.otf
          weight: 600
        - asset: assets/fonts/SfProDisplay-Bold.otf
          weight: 700
